name: Automated Web Pentest

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  workflow_dispatch:

jobs:
  pentest:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout source code
        uses: actions/checkout@v4

      - name: Set up Python 3.11
        uses: actions/setup-python@v5
        with:
          python-version: 3.11

      - name: Install dependencies
        run: |
          python3 -m venv venv
          source venv/bin/activate
          pip install -r requirements.txt

      - name: Run automated web pentest
        run: |
          source venv/bin/activate
          python3 main.py

      - name: Upload report artifacts
        uses: actions/upload-artifact@v4
        with:
          name: pentest-report
          path: output/
